[theme]
# Primary accent color for interactive elements.
primaryColor = "#0083B8"

# Background color for the main content area.
backgroundColor = "#FDFBE3"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#0083B8"

# Color used for almost all text.
textColor = "#000"